version: '3.2'

services:
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: "${NEXUS_DATA_VOLUME}"
        target: /nexus-data
    environment:
      NEXUS_CONTEXT: /
  nginx:
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - nexus